name : NextLevel
services:
  # Frontend React.js
  webapp:
    image: node:22
    profiles:
      - front-builder
    working_dir: /usr/src/app
    environment:
      API_EP_URI: /api/v1
      RT_API_EP_URI: /wsapi
    volumes:
      - ./src/app:/usr/src/app
      - app-static:/usr/src/app/build
    command: bash -c "npm install && npm run build"
    # Change if serving the frontend in dev mode

  # MongoDB Database
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    network:
      - back
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongodb_data:/data/db

  # Node.js Backend
  backend:
    image: node:22-alpine 
    build: 
      dockerfile: Dockerfile
    restart : always
    working_dir: /usr/src/app
    volumes:
      - ./api:/usr/src/app
    network:
      - back
    command: bash -c "npm install && npm start"

volumes:
  app-static:
  mongodb_data:

networks :
  back:
  